### ISSUE TITLE
Access to .local/share

### ISSUE THREAD

**Issue by steko** [alexlarsson/nightly-build-apps#2]
Hello,
I'm filing an issue here in the hope that it's the right place to bring up this request.

I've installed `org.inkscape.InkscapeDevel` and I'm enjoying the _Font Features_ that [landed in trunk a few months ago](http://tavmjong.free.fr/blog/?p=1442). Most of my fonts, including those with OpenType features that I'd like very much to try, are not in `/usr/share/fonts` but rather in `~/.local/share/fonts`.

In the _Preferences_ dialog I see the following paths under _System data_:
- /app/share
- /usr/share

I don't see a straightforward method to point Inkscape to the `.local` directory for data and other shared assets.

**Comment by alexlarsson** [comment]
I don't really know much about inkscape as such, but xdg-app and makes ~/.local/share/fonts (or ~/.fonts if that exists but the previous does not) as /run/host/user-fonts, and sets up fontconfig (via /etc/fonts/conf.d/50-xdg-app.conf in the sandbox) so that these fonts will be found by the system.

**Comment by alexlarsson** [comment]
So, this should "just work".

**Comment by alexlarsson** [comment]
Actually, it seems like there might be a bug in the fontconfig configuration that makes this not work...

**Comment by alexlarsson** [comment]
Yeah, seems /run/host/user-fonts needs to be added to the fontconfig config.

**Comment by steko** [comment]
Just to give more context: I'm on Debian sid. There is a `~/.var/app/org.inkscape.InkscapeDevel/cache/fontconfig` directory with some files, no idea if each file corresponds to a font.

**Comment by alexlarsson** [comment]
I will make an update to the gnome runtime next week that should hopefully fix this.

**Comment by steko** [comment]
Thanks for this and for all your work on xdg-app!

**Comment by alexlarsson** [comment]
Can you try "xdg-app update-runtime --user org.gnome.Platfom 3.18", it should now have your user-installed fonts available.

**Comment by steko** [comment]
It works! :+1:
