### ISSUE TITLE
404 when downloading Qt for Scribus

### ISSUE THREAD

**Issue by jurf** [alexlarsson/nightly-build-apps#6]
Also there are a lot of deps missing for Scribus. I spent quite a lot of time building a package for Scribus before someone pointed me to this so I’ll try to make a PR.

Small question however, wouldn’t it be easier to build upon the KDE runtime?

**Comment by alexlarsson** [comment]
It sure would, this build is quite ancident. Even nicer would be an upstream scribus flatpak :)

**Comment by alexlarsson** [comment]
ancient, not ancident.

**Comment by jurf** [comment]
Well, it kinda happened. It lives at https://github.com/jurf/scribus-flatpak for now.
